# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Cypress Tests with installation job

on: [push]

jobs:
  install:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node16.13.0-chrome95-ff94
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: yarn
      - run: yarn build

      - name: Save build folder
        uses: actions/upload-artifact@v2
        with:
          name: build
          if-no-files-found: error
          path: build

      # - name: Cypress install
      #   uses: cypress-io/github-action@v2
      #   with:
      #     runTests: false
      #     build: yarn build

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: yarn serve:build
